version: '3.7'

networks:
  default:
    external: true
    name: sagemaker-local

services:
  minio:
    image: minio/minio:RELEASE.2021-07-08T01-15-01Z
    ports:
      - "9000:9000"
    command: gateway azure
    environment:
      - MINIO_ACCESS_KEY=${DR_LOCAL_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${DR_LOCAL_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${DR_LOCAL_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DR_LOCAL_SECRET_ACCESS_KEY}

